baseURL: "https://www.ipyth.com"
title: "Website"

theme: ["docsy"]

metaDataFormat: "yaml"
# sectionPagesMenu: "main"

# Language settings
contentDir: "content/zh"
defaultContentLanguage: "zh"
defaultContentLanguageInSubdir: false

# Highlighting config.
pygmentsCodeFences: true
pygmentsUseClasses: false
pygmentsUseClassic: false
pygmentsStyle: "emacs"

permalinks:
  blog: "/:section/:year/:month/:day/:filename/"

markup:
  goldmark:
    renderer:
      unsafe: true
