baseURL: "https://www.ipyth.com"
title: "Website"

theme: ["ananke"]

metaDataFormat: "yaml"
sectionPagesMenu: "main"

# Language settings
contentDir: "content/zh"
defaultContentLanguage: "zh"
defaultContentLanguageInSubdir: false

permalinks:
  blog: "/:section/:year/:month/:day/:filename/"
