# params:
copyright: "LH"
github: "https://github.com/luohu1/website"
github_repo: "https://github.com/luohu1/website"

time_format_blog: "2006-01-02"
time_format_default: "2006-01-02 15:04PM Mon"

# Search settings
offlineSearch: true
offlineSearchSummaryLength: 70
offlineSearchMaxResults: 10

links:
  user:
    - name: "User mailing list"
      url: "https://github.com/luohu1"
      icon: "fa fa-envelope"
  developer:
    - name: "GitHub"
      url: "https://github.com/luohu1"
      icon: "fab fa-github"
